spring:
  application:
    name: tradeBook

  datasource:
    url: jdbc:mysql://localhost:3306/tradebook
    username: mysql
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE    # Logs SQL parameters
      org.springframework.jdbc.core.JdbcTemplate: DEBUG    # Logs database interaction
      org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG # Logs datasource interactions
      org.springframework.jdbc.BadSqlGrammarException: ERROR   # Logs SQL syntax errors
